spring:
  task:
    execution:
      pool:
        core-size: 100
mqtt:
  qos-level: 1
  server-url: ""
  topic: ""
  retain-messages: true
test:
  config:
    amount-of-data-points: 100
    message-delay: 100
    token-prefix: "TestDevice_"
    includeCreationTimestamp: true
    ttl: 60
    maximum-client-index: ${spring.task.execution.pool.core-size}
    minimum-client-index: 1
    retain-connection: true